- name: Build US telegram bot
  hosts: localhost
  connection: local
  tasks:
    - name: Build docker image
      community.docker.docker_image:
        name: bot_image
        force_source: true
        source: build
        build:
          path: /home/ubnt/actions-runner/_work/US_parser/US_parser
          dockerfile: .docker/Dockerfile

    - name: Run docker container
      docker_container:
        name: bot
        image: bot_image
        restart: true
        recreate: true
        etc_hosts:
          us3.radionet.com.ua: 192.168.100.223
          bill-admin2.radionet.com.ua: 10.255.255.234
        env:
          user: "{{ GH_US_USER }}"
          pass: "{{ GH_US_PASSWORD}}"
          API_TELEGRAM: "{{ GH_API_TELEGRAM }}"